import './globals.css'
import Navber from './components/Navigation/navber'
import Footer from './components/footer'
// import { Poppins } from 'next/font/google';
import { IBM_Plex_Sans } from 'next/font/google';
import Head from 'next/head';

const ibm = IBM_Plex_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-IBM_Plex_Sans',
  weight: ['100', '200', '300', '400', '500', '600', '700',]

})


export const metadata = {
  title: 'Artxcore',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/icon-01.png" />
      </Head>
      <body className={`${ibm.className}`}>
        <Navber></Navber>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
